//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="ObmenCreationSoapBinding", Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ObmenCreation : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback PostOrdersOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostRequestsOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostSNOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostPartnersOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostTovarsOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostDefectClientOperationCompleted;
    
    private System.Threading.SendOrPostCallback PostManagerOperationCompleted;
    
    /// <remarks/>
    public ObmenCreation() {
        this.Url = "http://31.13.35.34/dyson_share_111/ws/ObmenCreation.1cws";
    }
    
    /// <remarks/>
    public event PostOrdersCompletedEventHandler PostOrdersCompleted;
    
    /// <remarks/>
    public event PostRequestsCompletedEventHandler PostRequestsCompleted;
    
    /// <remarks/>
    public event PostSNCompletedEventHandler PostSNCompleted;
    
    /// <remarks/>
    public event PostPartnersCompletedEventHandler PostPartnersCompleted;
    
    /// <remarks/>
    public event PostTovarsCompletedEventHandler PostTovarsCompleted;
    
    /// <remarks/>
    public event PostDefectClientCompletedEventHandler PostDefectClientCompleted;
    
    /// <remarks/>
    public event PostManagerCompletedEventHandler PostManagerCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostOrders", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostOrders(ПакетЗаказов Pack) {
        object[] results = this.Invoke("PostOrders", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostOrders(ПакетЗаказов Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostOrders", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostOrders(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostOrdersAsync(ПакетЗаказов Pack) {
        this.PostOrdersAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostOrdersAsync(ПакетЗаказов Pack, object userState) {
        if ((this.PostOrdersOperationCompleted == null)) {
            this.PostOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostOrdersOperationCompleted);
        }
        this.InvokeAsync("PostOrders", new object[] {
                    Pack}, this.PostOrdersOperationCompleted, userState);
    }
    
    private void OnPostOrdersOperationCompleted(object arg) {
        if ((this.PostOrdersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostOrdersCompleted(this, new PostOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostRequests", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostRequests(ПакетЗаявок Pack) {
        object[] results = this.Invoke("PostRequests", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostRequests(ПакетЗаявок Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostRequests", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostRequests(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostRequestsAsync(ПакетЗаявок Pack) {
        this.PostRequestsAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostRequestsAsync(ПакетЗаявок Pack, object userState) {
        if ((this.PostRequestsOperationCompleted == null)) {
            this.PostRequestsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostRequestsOperationCompleted);
        }
        this.InvokeAsync("PostRequests", new object[] {
                    Pack}, this.PostRequestsOperationCompleted, userState);
    }
    
    private void OnPostRequestsOperationCompleted(object arg) {
        if ((this.PostRequestsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostRequestsCompleted(this, new PostRequestsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostSN", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostSN(ПакетРегистрация Pack) {
        object[] results = this.Invoke("PostSN", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostSN(ПакетРегистрация Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostSN", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostSN(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostSNAsync(ПакетРегистрация Pack) {
        this.PostSNAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostSNAsync(ПакетРегистрация Pack, object userState) {
        if ((this.PostSNOperationCompleted == null)) {
            this.PostSNOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostSNOperationCompleted);
        }
        this.InvokeAsync("PostSN", new object[] {
                    Pack}, this.PostSNOperationCompleted, userState);
    }
    
    private void OnPostSNOperationCompleted(object arg) {
        if ((this.PostSNCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostSNCompleted(this, new PostSNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostPartners", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostPartners(ПакетКонтрагентов Pack) {
        object[] results = this.Invoke("PostPartners", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostPartners(ПакетКонтрагентов Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostPartners", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostPartners(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostPartnersAsync(ПакетКонтрагентов Pack) {
        this.PostPartnersAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostPartnersAsync(ПакетКонтрагентов Pack, object userState) {
        if ((this.PostPartnersOperationCompleted == null)) {
            this.PostPartnersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostPartnersOperationCompleted);
        }
        this.InvokeAsync("PostPartners", new object[] {
                    Pack}, this.PostPartnersOperationCompleted, userState);
    }
    
    private void OnPostPartnersOperationCompleted(object arg) {
        if ((this.PostPartnersCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostPartnersCompleted(this, new PostPartnersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostTovars", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostTovars(ПакетНоменклатуры Pack) {
        object[] results = this.Invoke("PostTovars", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostTovars(ПакетНоменклатуры Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostTovars", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostTovars(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostTovarsAsync(ПакетНоменклатуры Pack) {
        this.PostTovarsAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostTovarsAsync(ПакетНоменклатуры Pack, object userState) {
        if ((this.PostTovarsOperationCompleted == null)) {
            this.PostTovarsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostTovarsOperationCompleted);
        }
        this.InvokeAsync("PostTovars", new object[] {
                    Pack}, this.PostTovarsOperationCompleted, userState);
    }
    
    private void OnPostTovarsOperationCompleted(object arg) {
        if ((this.PostTovarsCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostTovarsCompleted(this, new PostTovarsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostDefectClient", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostDefectClient(ПакетДефектыКлиента Pack) {
        object[] results = this.Invoke("PostDefectClient", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostDefectClient(ПакетДефектыКлиента Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostDefectClient", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostDefectClient(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostDefectClientAsync(ПакетДефектыКлиента Pack) {
        this.PostDefectClientAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostDefectClientAsync(ПакетДефектыКлиента Pack, object userState) {
        if ((this.PostDefectClientOperationCompleted == null)) {
            this.PostDefectClientOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostDefectClientOperationCompleted);
        }
        this.InvokeAsync("PostDefectClient", new object[] {
                    Pack}, this.PostDefectClientOperationCompleted, userState);
    }
    
    private void OnPostDefectClientOperationCompleted(object arg) {
        if ((this.PostDefectClientCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostDefectClientCompleted(this, new PostDefectClientCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://31.13.35.34/dyson_share_111#ObmenCreation:PostManager", RequestNamespace="http://31.13.35.34/dyson_share_111", ResponseNamespace="http://31.13.35.34/dyson_share_111", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return")]
    public ПакетОтвета PostManager(ПакетПользователи Pack) {
        object[] results = this.Invoke("PostManager", new object[] {
                    Pack});
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginPostManager(ПакетПользователи Pack, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("PostManager", new object[] {
                    Pack}, callback, asyncState);
    }
    
    /// <remarks/>
    public ПакетОтвета EndPostManager(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((ПакетОтвета)(results[0]));
    }
    
    /// <remarks/>
    public void PostManagerAsync(ПакетПользователи Pack) {
        this.PostManagerAsync(Pack, null);
    }
    
    /// <remarks/>
    public void PostManagerAsync(ПакетПользователи Pack, object userState) {
        if ((this.PostManagerOperationCompleted == null)) {
            this.PostManagerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPostManagerOperationCompleted);
        }
        this.InvokeAsync("PostManager", new object[] {
                    Pack}, this.PostManagerOperationCompleted, userState);
    }
    
    private void OnPostManagerOperationCompleted(object arg) {
        if ((this.PostManagerCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PostManagerCompleted(this, new PostManagerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетЗаказов {
    
    private string iD_PackField;
    
    private ЗаказКлиента[] orderField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Order")]
    public ЗаказКлиента[] Order {
        get {
            return this.orderField;
        }
        set {
            this.orderField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаказКлиента {
    
    private System.DateTime createDateField;
    
    private System.Nullable<System.DateTime> date_Tk_LoadField;
    
    private System.DateTime deliveryDateField;
    
    private System.Nullable<int> timeDeliveryFromField;
    
    private System.Nullable<int> timeDeliveryToField;
    
    private System.DateTime tK_PlandateField;
    
    private System.DateTime completeDateField;
    
    private System.DateTime modifyDateField;
    
    private string orderIDField;
    
    private int orderIdPublicField;
    
    private string orderStatusField;
    
    private string tK_TrackField;
    
    private string tkField;
    
    private System.Nullable<int> orderTypeField;
    
    private string payTypeField;
    
    private string logisticCommentField;
    
    private decimal orderSumRUBField;
    
    private int payTransactionField;
    
    private System.Nullable<System.DateTime> dataReleaseHField;
    
    private System.Nullable<System.DateTime> dataReleaseMField;
    
    private string payTransactionODMField;
    
    private System.DateTime dataCheckMField;
    
    private System.DateTime payDateField;
    
    private string creditStatusField;
    
    private System.Nullable<decimal> creditSummField;
    
    private string paper_idField;
    
    private System.Nullable<decimal> inCashField;
    
    private System.Nullable<decimal> onLinePaidField;
    
    private string panTypeField;
    
    private decimal deliveryCostField;
    
    private decimal promoSumField;
    
    private string commentField;
    
    private string managerField;
    
    private string managerPhoneField;
    
    private string iNNField;
    
    private string kPPField;
    
    private string phoneNumberField;
    
    private string emailField;
    
    private string courierInfoField;
    
    private string regionField;
    
    private string localityField;
    
    private string streetField;
    
    private string kladrField;
    
    private string metroField;
    
    private string houseField;
    
    private string buildingField;
    
    private string korpField;
    
    private string flatField;
    
    private string entranceField;
    
    private string sOCR_RegionField;
    
    private string sOCR_LocalityField;
    
    private string sOCR_CityField;
    
    private string sOCR_StreetField;
    
    private string sOCR_AreaField;
    
    private string fLOORField;
    
    private string intercomField;
    
    private string cityField;
    
    private string distanceFromMKADField;
    
    private string areaField;
    
    private string numberDepartureField;
    
    private string latField;
    
    private string lonField;
    
    private System.DateTime shipDateField;
    
    private string dysonChannelCodeField;
    
    private string organizationField;
    
    private string warehouseCodeField;
    
    private string commentTKField;
    
    private ЗаказКлиентаTovars[] tovarsField;
    
    /// <remarks/>
    public System.DateTime CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> Date_Tk_Load {
        get {
            return this.date_Tk_LoadField;
        }
        set {
            this.date_Tk_LoadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime deliveryDate {
        get {
            return this.deliveryDateField;
        }
        set {
            this.deliveryDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> TimeDeliveryFrom {
        get {
            return this.timeDeliveryFromField;
        }
        set {
            this.timeDeliveryFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> TimeDeliveryTo {
        get {
            return this.timeDeliveryToField;
        }
        set {
            this.timeDeliveryToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime TK_Plandate {
        get {
            return this.tK_PlandateField;
        }
        set {
            this.tK_PlandateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime completeDate {
        get {
            return this.completeDateField;
        }
        set {
            this.completeDateField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime modifyDate {
        get {
            return this.modifyDateField;
        }
        set {
            this.modifyDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string orderID {
        get {
            return this.orderIDField;
        }
        set {
            this.orderIDField = value;
        }
    }
    
    /// <remarks/>
    public int orderIdPublic {
        get {
            return this.orderIdPublicField;
        }
        set {
            this.orderIdPublicField = value;
        }
    }
    
    /// <remarks/>
    public string OrderStatus {
        get {
            return this.orderStatusField;
        }
        set {
            this.orderStatusField = value;
        }
    }
    
    /// <remarks/>
    public string TK_Track {
        get {
            return this.tK_TrackField;
        }
        set {
            this.tK_TrackField = value;
        }
    }
    
    /// <remarks/>
    public string TK {
        get {
            return this.tkField;
        }
        set {
            this.tkField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> OrderType {
        get {
            return this.orderTypeField;
        }
        set {
            this.orderTypeField = value;
        }
    }
    
    /// <remarks/>
    public string PayType {
        get {
            return this.payTypeField;
        }
        set {
            this.payTypeField = value;
        }
    }
    
    /// <remarks/>
    public string LogisticComment {
        get {
            return this.logisticCommentField;
        }
        set {
            this.logisticCommentField = value;
        }
    }
    
    /// <remarks/>
    public decimal OrderSumRUB {
        get {
            return this.orderSumRUBField;
        }
        set {
            this.orderSumRUBField = value;
        }
    }
    
    /// <remarks/>
    public int PayTransaction {
        get {
            return this.payTransactionField;
        }
        set {
            this.payTransactionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DataReleaseH {
        get {
            return this.dataReleaseHField;
        }
        set {
            this.dataReleaseHField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DataReleaseM {
        get {
            return this.dataReleaseMField;
        }
        set {
            this.dataReleaseMField = value;
        }
    }
    
    /// <remarks/>
    public string PayTransactionODM {
        get {
            return this.payTransactionODMField;
        }
        set {
            this.payTransactionODMField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime DataCheckM {
        get {
            return this.dataCheckMField;
        }
        set {
            this.dataCheckMField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime PayDate {
        get {
            return this.payDateField;
        }
        set {
            this.payDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string CreditStatus {
        get {
            return this.creditStatusField;
        }
        set {
            this.creditStatusField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> CreditSumm {
        get {
            return this.creditSummField;
        }
        set {
            this.creditSummField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string paper_id {
        get {
            return this.paper_idField;
        }
        set {
            this.paper_idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> InCash {
        get {
            return this.inCashField;
        }
        set {
            this.inCashField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<decimal> OnLinePaid {
        get {
            return this.onLinePaidField;
        }
        set {
            this.onLinePaidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PanType {
        get {
            return this.panTypeField;
        }
        set {
            this.panTypeField = value;
        }
    }
    
    /// <remarks/>
    public decimal DeliveryCost {
        get {
            return this.deliveryCostField;
        }
        set {
            this.deliveryCostField = value;
        }
    }
    
    /// <remarks/>
    public decimal PromoSum {
        get {
            return this.promoSumField;
        }
        set {
            this.promoSumField = value;
        }
    }
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    public string Manager {
        get {
            return this.managerField;
        }
        set {
            this.managerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ManagerPhone {
        get {
            return this.managerPhoneField;
        }
        set {
            this.managerPhoneField = value;
        }
    }
    
    /// <remarks/>
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public string CourierInfo {
        get {
            return this.courierInfoField;
        }
        set {
            this.courierInfoField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Region {
        get {
            return this.regionField;
        }
        set {
            this.regionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Locality {
        get {
            return this.localityField;
        }
        set {
            this.localityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Street {
        get {
            return this.streetField;
        }
        set {
            this.streetField = value;
        }
    }
    
    /// <remarks/>
    public string kladr {
        get {
            return this.kladrField;
        }
        set {
            this.kladrField = value;
        }
    }
    
    /// <remarks/>
    public string Metro {
        get {
            return this.metroField;
        }
        set {
            this.metroField = value;
        }
    }
    
    /// <remarks/>
    public string House {
        get {
            return this.houseField;
        }
        set {
            this.houseField = value;
        }
    }
    
    /// <remarks/>
    public string Building {
        get {
            return this.buildingField;
        }
        set {
            this.buildingField = value;
        }
    }
    
    /// <remarks/>
    public string Korp {
        get {
            return this.korpField;
        }
        set {
            this.korpField = value;
        }
    }
    
    /// <remarks/>
    public string Flat {
        get {
            return this.flatField;
        }
        set {
            this.flatField = value;
        }
    }
    
    /// <remarks/>
    public string Entrance {
        get {
            return this.entranceField;
        }
        set {
            this.entranceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOCR_Region {
        get {
            return this.sOCR_RegionField;
        }
        set {
            this.sOCR_RegionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOCR_Locality {
        get {
            return this.sOCR_LocalityField;
        }
        set {
            this.sOCR_LocalityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOCR_City {
        get {
            return this.sOCR_CityField;
        }
        set {
            this.sOCR_CityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOCR_Street {
        get {
            return this.sOCR_StreetField;
        }
        set {
            this.sOCR_StreetField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string SOCR_Area {
        get {
            return this.sOCR_AreaField;
        }
        set {
            this.sOCR_AreaField = value;
        }
    }
    
    /// <remarks/>
    public string FLOOR {
        get {
            return this.fLOORField;
        }
        set {
            this.fLOORField = value;
        }
    }
    
    /// <remarks/>
    public string Intercom {
        get {
            return this.intercomField;
        }
        set {
            this.intercomField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string DistanceFromMKAD {
        get {
            return this.distanceFromMKADField;
        }
        set {
            this.distanceFromMKADField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Area {
        get {
            return this.areaField;
        }
        set {
            this.areaField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string NumberDeparture {
        get {
            return this.numberDepartureField;
        }
        set {
            this.numberDepartureField = value;
        }
    }
    
    /// <remarks/>
    public string Lat {
        get {
            return this.latField;
        }
        set {
            this.latField = value;
        }
    }
    
    /// <remarks/>
    public string Lon {
        get {
            return this.lonField;
        }
        set {
            this.lonField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ShipDate {
        get {
            return this.shipDateField;
        }
        set {
            this.shipDateField = value;
        }
    }
    
    /// <remarks/>
    public string DysonChannelCode {
        get {
            return this.dysonChannelCodeField;
        }
        set {
            this.dysonChannelCodeField = value;
        }
    }
    
    /// <remarks/>
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseCode {
        get {
            return this.warehouseCodeField;
        }
        set {
            this.warehouseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string CommentTK {
        get {
            return this.commentTKField;
        }
        set {
            this.commentTKField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tovars")]
    public ЗаказКлиентаTovars[] Tovars {
        get {
            return this.tovarsField;
        }
        set {
            this.tovarsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаказКлиентаTovars {
    
    private string tovarCodField;
    
    private decimal kolField;
    
    private decimal tovarSumField;
    
    private string typePriceCodeField;
    
    private decimal rRCField;
    
    private string snField;
    
    private int nDS_SField;
    
    private decimal nDSField;
    
    private bool productsCanceledField;
    
    private string reasonCancellationField;
    
    private string pROMOCODEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TovarCod {
        get {
            return this.tovarCodField;
        }
        set {
            this.tovarCodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Kol {
        get {
            return this.kolField;
        }
        set {
            this.kolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal TovarSum {
        get {
            return this.tovarSumField;
        }
        set {
            this.tovarSumField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string TypePriceCode {
        get {
            return this.typePriceCodeField;
        }
        set {
            this.typePriceCodeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal RRC {
        get {
            return this.rRCField;
        }
        set {
            this.rRCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string SN {
        get {
            return this.snField;
        }
        set {
            this.snField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int NDS_S {
        get {
            return this.nDS_SField;
        }
        set {
            this.nDS_SField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal NDS {
        get {
            return this.nDSField;
        }
        set {
            this.nDSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool ProductsCanceled {
        get {
            return this.productsCanceledField;
        }
        set {
            this.productsCanceledField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ReasonCancellation {
        get {
            return this.reasonCancellationField;
        }
        set {
            this.reasonCancellationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PROMOCODE {
        get {
            return this.pROMOCODEField;
        }
        set {
            this.pROMOCODEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class Пользователи {
    
    private bool markDeletionField;
    
    private string nameField;
    
    /// <remarks/>
    public bool MarkDeletion {
        get {
            return this.markDeletionField;
        }
        set {
            this.markDeletionField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетПользователи {
    
    private string iD_PackField;
    
    private Пользователи[] userField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("User")]
    public Пользователи[] User {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ДефектыСоСловКлиента {
    
    private bool markDeletionField;
    
    private string nameField;
    
    /// <remarks/>
    public bool MarkDeletion {
        get {
            return this.markDeletionField;
        }
        set {
            this.markDeletionField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетДефектыКлиента {
    
    private string iD_PackField;
    
    private ДефектыСоСловКлиента[] defectClientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DefectClient")]
    public ДефектыСоСловКлиента[] DefectClient {
        get {
            return this.defectClientField;
        }
        set {
            this.defectClientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class Номенклатура {
    
    private bool markDeletionField;
    
    private string articleField;
    
    private string nameField;
    
    private string fullNameField;
    
    /// <remarks/>
    public bool MarkDeletion {
        get {
            return this.markDeletionField;
        }
        set {
            this.markDeletionField = value;
        }
    }
    
    /// <remarks/>
    public string Article {
        get {
            return this.articleField;
        }
        set {
            this.articleField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string FullName {
        get {
            return this.fullNameField;
        }
        set {
            this.fullNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетНоменклатуры {
    
    private string iD_PackField;
    
    private Номенклатура[] tovarField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Tovar")]
    public Номенклатура[] Tovar {
        get {
            return this.tovarField;
        }
        set {
            this.tovarField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class Контрагенты {
    
    private bool markDeletionField;
    
    private bool legalField;
    
    private string iNNField;
    
    private string kPPField;
    
    private string phoneNumberField;
    
    private string nameField;
    
    private string legalPhoneNumberField;
    
    private string fIO_FField;
    
    private string name_FField;
    
    private string middleName_FField;
    
    private string emailField;
    
    private bool fSSMSField;
    
    private bool fSEField;
    
    private bool fMEField;
    
    private bool fSCOField;
    
    private bool fMCOField;
    
    private bool fMSMSField;
    
    private bool fSRField;
    
    private bool fMRField;
    
    private string iDDepersonalizedClientField;
    
    private bool thereAreLKField;
    
    private string fIASField;
    
    private string objectTypeListField;
    
    private string fIOYOField;
    
    private string postYOField;
    
    private string mobTelYOField;
    
    private string emailYOField;
    
    private string fIOYDField;
    
    private string postYDField;
    
    private string mobTelYDField;
    
    private string emailYDField;
    
    private bool pointSaleField;
    
    private string dysonChannelCodeField;
    
    private string statusClientField;
    
    /// <remarks/>
    public bool MarkDeletion {
        get {
            return this.markDeletionField;
        }
        set {
            this.markDeletionField = value;
        }
    }
    
    /// <remarks/>
    public bool Legal {
        get {
            return this.legalField;
        }
        set {
            this.legalField = value;
        }
    }
    
    /// <remarks/>
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string LegalPhoneNumber {
        get {
            return this.legalPhoneNumberField;
        }
        set {
            this.legalPhoneNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FIO_F {
        get {
            return this.fIO_FField;
        }
        set {
            this.fIO_FField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Name_F {
        get {
            return this.name_FField;
        }
        set {
            this.name_FField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MiddleName_F {
        get {
            return this.middleName_FField;
        }
        set {
            this.middleName_FField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Email {
        get {
            return this.emailField;
        }
        set {
            this.emailField = value;
        }
    }
    
    /// <remarks/>
    public bool FSSMS {
        get {
            return this.fSSMSField;
        }
        set {
            this.fSSMSField = value;
        }
    }
    
    /// <remarks/>
    public bool FSE {
        get {
            return this.fSEField;
        }
        set {
            this.fSEField = value;
        }
    }
    
    /// <remarks/>
    public bool FME {
        get {
            return this.fMEField;
        }
        set {
            this.fMEField = value;
        }
    }
    
    /// <remarks/>
    public bool FSCO {
        get {
            return this.fSCOField;
        }
        set {
            this.fSCOField = value;
        }
    }
    
    /// <remarks/>
    public bool FMCO {
        get {
            return this.fMCOField;
        }
        set {
            this.fMCOField = value;
        }
    }
    
    /// <remarks/>
    public bool FMSMS {
        get {
            return this.fMSMSField;
        }
        set {
            this.fMSMSField = value;
        }
    }
    
    /// <remarks/>
    public bool FSR {
        get {
            return this.fSRField;
        }
        set {
            this.fSRField = value;
        }
    }
    
    /// <remarks/>
    public bool FMR {
        get {
            return this.fMRField;
        }
        set {
            this.fMRField = value;
        }
    }
    
    /// <remarks/>
    public string IDDepersonalizedClient {
        get {
            return this.iDDepersonalizedClientField;
        }
        set {
            this.iDDepersonalizedClientField = value;
        }
    }
    
    /// <remarks/>
    public bool ThereAreLK {
        get {
            return this.thereAreLKField;
        }
        set {
            this.thereAreLKField = value;
        }
    }
    
    /// <remarks/>
    public string FIAS {
        get {
            return this.fIASField;
        }
        set {
            this.fIASField = value;
        }
    }
    
    /// <remarks/>
    public string ObjectTypeList {
        get {
            return this.objectTypeListField;
        }
        set {
            this.objectTypeListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FIOYO {
        get {
            return this.fIOYOField;
        }
        set {
            this.fIOYOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PostYO {
        get {
            return this.postYOField;
        }
        set {
            this.postYOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MobTelYO {
        get {
            return this.mobTelYOField;
        }
        set {
            this.mobTelYOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EmailYO {
        get {
            return this.emailYOField;
        }
        set {
            this.emailYOField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FIOYD {
        get {
            return this.fIOYDField;
        }
        set {
            this.fIOYDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string PostYD {
        get {
            return this.postYDField;
        }
        set {
            this.postYDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string MobTelYD {
        get {
            return this.mobTelYDField;
        }
        set {
            this.mobTelYDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string EmailYD {
        get {
            return this.emailYDField;
        }
        set {
            this.emailYDField = value;
        }
    }
    
    /// <remarks/>
    public bool PointSale {
        get {
            return this.pointSaleField;
        }
        set {
            this.pointSaleField = value;
        }
    }
    
    /// <remarks/>
    public string DysonChannelCode {
        get {
            return this.dysonChannelCodeField;
        }
        set {
            this.dysonChannelCodeField = value;
        }
    }
    
    /// <remarks/>
    public string StatusClient {
        get {
            return this.statusClientField;
        }
        set {
            this.statusClientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетКонтрагентов {
    
    private string iD_PackField;
    
    private Контрагенты[] partnerField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Partner")]
    public Контрагенты[] Partner {
        get {
            return this.partnerField;
        }
        set {
            this.partnerField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class РегистрацияСерийныхНомеровКлиентов {
    
    private bool markDeletionField;
    
    private string snField;
    
    private string iNNField;
    
    private string kPPField;
    
    private string phoneNumberField;
    
    private System.DateTime createDateField;
    
    private string articleField;
    
    private string typeGuaranteeField;
    
    private string shopField;
    
    private System.Nullable<System.DateTime> datePurchaseField;
    
    private string commentField;
    
    /// <remarks/>
    public bool MarkDeletion {
        get {
            return this.markDeletionField;
        }
        set {
            this.markDeletionField = value;
        }
    }
    
    /// <remarks/>
    public string SN {
        get {
            return this.snField;
        }
        set {
            this.snField = value;
        }
    }
    
    /// <remarks/>
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string Article {
        get {
            return this.articleField;
        }
        set {
            this.articleField = value;
        }
    }
    
    /// <remarks/>
    public string TypeGuarantee {
        get {
            return this.typeGuaranteeField;
        }
        set {
            this.typeGuaranteeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Shop {
        get {
            return this.shopField;
        }
        set {
            this.shopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date", IsNullable=true)]
    public System.Nullable<System.DateTime> DatePurchase {
        get {
            return this.datePurchaseField;
        }
        set {
            this.datePurchaseField = value;
        }
    }
    
    /// <remarks/>
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетРегистрация {
    
    private string iD_PackField;
    
    private РегистрацияСерийныхНомеровКлиентов[] regSNField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RegSN")]
    public РегистрацияСерийныхНомеровКлиентов[] RegSN {
        get {
            return this.regSNField;
        }
        set {
            this.regSNField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаявкаНаРемонт {
    
    private System.DateTime createDateField;
    
    private string documentNumberField;
    
    private string organizationField;
    
    private string iNNField;
    
    private string kPPField;
    
    private string phoneNumberField;
    
    private string warehouseCodeField;
    
    private string serviceOptionField;
    
    private string typeRepairField;
    
    private string articleField;
    
    private string snField;
    
    private System.Nullable<System.DateTime> dateDepartureField;
    
    private string masterField;
    
    private string shopField;
    
    private System.DateTime datePurchaseField;
    
    private string typeGuaranteeField;
    
    private bool renewalWarrantyField;
    
    private System.DateTime actualDateRepairExecutionField;
    
    private string informationClientField;
    
    private string internalCommentField;
    
    private bool violationOperationField;
    
    private System.Nullable<int> commentsResultRepairField;
    
    private string feedbackClientField;
    
    private ЗаявкаНаРемонтDefects[] defectsField;
    
    private ЗаявкаНаРемонтDefectsAccordingClient[] defectsAccordingClientField;
    
    private ЗаявкаНаРемонтSpares[] sparesField;
    
    private ЗаявкаНаРемонтServices[] servicesField;
    
    /// <remarks/>
    public System.DateTime CreateDate {
        get {
            return this.createDateField;
        }
        set {
            this.createDateField = value;
        }
    }
    
    /// <remarks/>
    public string DocumentNumber {
        get {
            return this.documentNumberField;
        }
        set {
            this.documentNumberField = value;
        }
    }
    
    /// <remarks/>
    public string Organization {
        get {
            return this.organizationField;
        }
        set {
            this.organizationField = value;
        }
    }
    
    /// <remarks/>
    public string INN {
        get {
            return this.iNNField;
        }
        set {
            this.iNNField = value;
        }
    }
    
    /// <remarks/>
    public string KPP {
        get {
            return this.kPPField;
        }
        set {
            this.kPPField = value;
        }
    }
    
    /// <remarks/>
    public string PhoneNumber {
        get {
            return this.phoneNumberField;
        }
        set {
            this.phoneNumberField = value;
        }
    }
    
    /// <remarks/>
    public string WarehouseCode {
        get {
            return this.warehouseCodeField;
        }
        set {
            this.warehouseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ServiceOption {
        get {
            return this.serviceOptionField;
        }
        set {
            this.serviceOptionField = value;
        }
    }
    
    /// <remarks/>
    public string TypeRepair {
        get {
            return this.typeRepairField;
        }
        set {
            this.typeRepairField = value;
        }
    }
    
    /// <remarks/>
    public string Article {
        get {
            return this.articleField;
        }
        set {
            this.articleField = value;
        }
    }
    
    /// <remarks/>
    public string SN {
        get {
            return this.snField;
        }
        set {
            this.snField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<System.DateTime> DateDeparture {
        get {
            return this.dateDepartureField;
        }
        set {
            this.dateDepartureField = value;
        }
    }
    
    /// <remarks/>
    public string Master {
        get {
            return this.masterField;
        }
        set {
            this.masterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string Shop {
        get {
            return this.shopField;
        }
        set {
            this.shopField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DatePurchase {
        get {
            return this.datePurchaseField;
        }
        set {
            this.datePurchaseField = value;
        }
    }
    
    /// <remarks/>
    public string TypeGuarantee {
        get {
            return this.typeGuaranteeField;
        }
        set {
            this.typeGuaranteeField = value;
        }
    }
    
    /// <remarks/>
    public bool RenewalWarranty {
        get {
            return this.renewalWarrantyField;
        }
        set {
            this.renewalWarrantyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime ActualDateRepairExecution {
        get {
            return this.actualDateRepairExecutionField;
        }
        set {
            this.actualDateRepairExecutionField = value;
        }
    }
    
    /// <remarks/>
    public string InformationClient {
        get {
            return this.informationClientField;
        }
        set {
            this.informationClientField = value;
        }
    }
    
    /// <remarks/>
    public string InternalComment {
        get {
            return this.internalCommentField;
        }
        set {
            this.internalCommentField = value;
        }
    }
    
    /// <remarks/>
    public bool ViolationOperation {
        get {
            return this.violationOperationField;
        }
        set {
            this.violationOperationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<int> CommentsResultRepair {
        get {
            return this.commentsResultRepairField;
        }
        set {
            this.commentsResultRepairField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string FeedbackClient {
        get {
            return this.feedbackClientField;
        }
        set {
            this.feedbackClientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Defects", IsNullable=true)]
    public ЗаявкаНаРемонтDefects[] Defects {
        get {
            return this.defectsField;
        }
        set {
            this.defectsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DefectsAccordingClient", IsNullable=true)]
    public ЗаявкаНаРемонтDefectsAccordingClient[] DefectsAccordingClient {
        get {
            return this.defectsAccordingClientField;
        }
        set {
            this.defectsAccordingClientField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Spares", IsNullable=true)]
    public ЗаявкаНаРемонтSpares[] Spares {
        get {
            return this.sparesField;
        }
        set {
            this.sparesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Services", IsNullable=true)]
    public ЗаявкаНаРемонтServices[] Services {
        get {
            return this.servicesField;
        }
        set {
            this.servicesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаявкаНаРемонтDefects {
    
    private string defectField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Defect {
        get {
            return this.defectField;
        }
        set {
            this.defectField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаявкаНаРемонтDefectsAccordingClient {
    
    private string defectAccordingClientField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DefectAccordingClient {
        get {
            return this.defectAccordingClientField;
        }
        set {
            this.defectAccordingClientField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаявкаНаРемонтSpares {
    
    private string spareField;
    
    private int requiredField;
    
    private int availabilityField;
    
    private decimal priceField;
    
    private bool paidField;
    
    private decimal amountField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Spare {
        get {
            return this.spareField;
        }
        set {
            this.spareField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Required {
        get {
            return this.requiredField;
        }
        set {
            this.requiredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Availability {
        get {
            return this.availabilityField;
        }
        set {
            this.availabilityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Paid {
        get {
            return this.paidField;
        }
        set {
            this.paidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ЗаявкаНаРемонтServices {
    
    private string masterField;
    
    private string serviceField;
    
    private int kolField;
    
    private decimal amountField;
    
    private bool paidField;
    
    private string contentField;
    
    private decimal priceField;
    
    /// <remarks/>
    public string Master {
        get {
            return this.masterField;
        }
        set {
            this.masterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Service {
        get {
            return this.serviceField;
        }
        set {
            this.serviceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int Kol {
        get {
            return this.kolField;
        }
        set {
            this.kolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool Paid {
        get {
            return this.paidField;
        }
        set {
            this.paidField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public decimal Price {
        get {
            return this.priceField;
        }
        set {
            this.priceField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетЗаявок {
    
    private string iD_PackField;
    
    private ЗаявкаНаРемонт[] requestField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Request")]
    public ЗаявкаНаРемонт[] Request {
        get {
            return this.requestField;
        }
        set {
            this.requestField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетОтвета {
    
    private string iD_PackField;
    
    private bool yesErrorField;
    
    private ПакетОтветаErrors[] errorsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public string ID_Pack {
        get {
            return this.iD_PackField;
        }
        set {
            this.iD_PackField = value;
        }
    }
    
    /// <remarks/>
    public bool YesError {
        get {
            return this.yesErrorField;
        }
        set {
            this.yesErrorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Errors", IsNullable=true)]
    public ПакетОтветаErrors[] Errors {
        get {
            return this.errorsField;
        }
        set {
            this.errorsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://31.13.35.34/dyson_share_111")]
public partial class ПакетОтветаErrors {
    
    private string idField;
    
    private string errorField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Error {
        get {
            return this.errorField;
        }
        set {
            this.errorField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostOrdersCompletedEventHandler(object sender, PostOrdersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostRequestsCompletedEventHandler(object sender, PostRequestsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostRequestsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostRequestsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostSNCompletedEventHandler(object sender, PostSNCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostSNCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostSNCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostPartnersCompletedEventHandler(object sender, PostPartnersCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostPartnersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostPartnersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostTovarsCompletedEventHandler(object sender, PostTovarsCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostTovarsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostTovarsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostDefectClientCompletedEventHandler(object sender, PostDefectClientCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostDefectClientCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostDefectClientCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void PostManagerCompletedEventHandler(object sender, PostManagerCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PostManagerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal PostManagerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public ПакетОтвета Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((ПакетОтвета)(this.results[0]));
        }
    }
}
