//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DysonPromocodeService.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://crm1ctest.dyson.ru/CRM_TEST", ConfigurationName="ServiceReference1.PromocodeStatusPortType")]
    public interface PromocodeStatusPortType {
        
        // CODEGEN: Контракт генерации сообщений с именем Promocode из пространства имен https://crm1ctest.dyson.ru/CRM_TEST не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="https://crm1ctest.dyson.ru/CRM_TEST#PromocodeStatus:GetStatus", ReplyAction="*")]
        DysonPromocodeService.ServiceReference1.GetStatusResponse GetStatus(DysonPromocodeService.ServiceReference1.GetStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://crm1ctest.dyson.ru/CRM_TEST#PromocodeStatus:GetStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<DysonPromocodeService.ServiceReference1.GetStatusResponse> GetStatusAsync(DysonPromocodeService.ServiceReference1.GetStatusRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatus", Namespace="https://crm1ctest.dyson.ru/CRM_TEST", Order=0)]
        public DysonPromocodeService.ServiceReference1.GetStatusRequestBody Body;
        
        public GetStatusRequest() {
        }
        
        public GetStatusRequest(DysonPromocodeService.ServiceReference1.GetStatusRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://crm1ctest.dyson.ru/CRM_TEST")]
    public partial class GetStatusRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Promocode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ArticleList;
        
        public GetStatusRequestBody() {
        }
        
        public GetStatusRequestBody(string Promocode, string ArticleList) {
            this.Promocode = Promocode;
            this.ArticleList = ArticleList;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatusResponse", Namespace="https://crm1ctest.dyson.ru/CRM_TEST", Order=0)]
        public DysonPromocodeService.ServiceReference1.GetStatusResponseBody Body;
        
        public GetStatusResponse() {
        }
        
        public GetStatusResponse(DysonPromocodeService.ServiceReference1.GetStatusResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="https://crm1ctest.dyson.ru/CRM_TEST")]
    public partial class GetStatusResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetStatusResponseBody() {
        }
        
        public GetStatusResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PromocodeStatusPortTypeChannel : DysonPromocodeService.ServiceReference1.PromocodeStatusPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PromocodeStatusPortTypeClient : System.ServiceModel.ClientBase<DysonPromocodeService.ServiceReference1.PromocodeStatusPortType>, DysonPromocodeService.ServiceReference1.PromocodeStatusPortType {
        
        public PromocodeStatusPortTypeClient() {
        }
        
        public PromocodeStatusPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PromocodeStatusPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocodeStatusPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PromocodeStatusPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DysonPromocodeService.ServiceReference1.GetStatusResponse DysonPromocodeService.ServiceReference1.PromocodeStatusPortType.GetStatus(DysonPromocodeService.ServiceReference1.GetStatusRequest request) {
            return base.Channel.GetStatus(request);
        }
        
        public string GetStatus(string Promocode, string ArticleList) {
            DysonPromocodeService.ServiceReference1.GetStatusRequest inValue = new DysonPromocodeService.ServiceReference1.GetStatusRequest();
            inValue.Body = new DysonPromocodeService.ServiceReference1.GetStatusRequestBody();
            inValue.Body.Promocode = Promocode;
            inValue.Body.ArticleList = ArticleList;
            DysonPromocodeService.ServiceReference1.GetStatusResponse retVal = ((DysonPromocodeService.ServiceReference1.PromocodeStatusPortType)(this)).GetStatus(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DysonPromocodeService.ServiceReference1.GetStatusResponse> DysonPromocodeService.ServiceReference1.PromocodeStatusPortType.GetStatusAsync(DysonPromocodeService.ServiceReference1.GetStatusRequest request) {
            return base.Channel.GetStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<DysonPromocodeService.ServiceReference1.GetStatusResponse> GetStatusAsync(string Promocode, string ArticleList) {
            DysonPromocodeService.ServiceReference1.GetStatusRequest inValue = new DysonPromocodeService.ServiceReference1.GetStatusRequest();
            inValue.Body = new DysonPromocodeService.ServiceReference1.GetStatusRequestBody();
            inValue.Body.Promocode = Promocode;
            inValue.Body.ArticleList = ArticleList;
            return ((DysonPromocodeService.ServiceReference1.PromocodeStatusPortType)(this)).GetStatusAsync(inValue);
        }
    }
}
